version: '2'
services:
  backend:
    container_name: adulto-mayor-compensar
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app